#This function identifies the number, location, and size of blobs within a single image by
#using one of the skimage.feature blob detection functions. 
#It is passed an image [project_image] as a 2D or 3D array, the maximum standard deviation 
# [sig_max] to accept when searching for a blob (which is analogous to maximum allowable 
# blob size), and the intensity threshold at which it will first consider a blob to be found
# at [min_thr] computed as a fraction of the maximum intensity in the image. 
def blobs (project_image,sig_max,min_thr): 
    
    blobs_dog = blob_dog(project_image, max_sigma=sig_max, threshold=min_thr) #uses the 
    #built in 'Blob Detection' function that computes the Laplace of the Gaussian matrix 
    #of the image to identify, locate, and size blobs. 
    
    x = blobs_dog[:,1] #extracts the x coordinate information for each blob
    
    y = blobs_dog[:,0] #extracts the y coordinate information for each blob
    
    r = blobs_dog[:,3] #extracts the radius information for each blob
    
    blob_count = len(blobs_dog[:,0]) #determines the number of total blobs by counting how 
    #many blob entries were generated by the blobs_log function
    
    return x, y, r, blob_count #returns the x,y position and radius r size information,
    #and the number of total blobs. Radius is the computed
    #blob size if it were to form a perfect circle
